apiVersion: v1
kind: ConfigMap

metadata:
  name: redis-config
  namespace: banking

data:

  redis.conf: |

    appendonly yes

    appendfsync everysec

    protected-mode yes

    maxmemory 2gb

    maxmemory-policy allkeys-lru

    tcp-keepalive 300

    timeout 0

    save 900 1
    save 300 10
    save 60 10000