apiVersion: v1
kind: ConfigMap

metadata:
  name: loan-service-config
  namespace: banking

data:

  SPRING_APPLICATION_NAME: loan-service

  SERVER_PORT: "8080"

  DB_HOST: postgres-loan

  DB_PORT: "5432"

  DB_NAME: loandb

  KAFKA_BOOTSTRAP_SERVERS: kafka:9092

  REDIS_HOST: redis

  REDIS_PORT: "6379"

  CUSTOMER_SERVICE_URL: http://customer-service

  PAYMENT_SERVICE_URL: http://payment-service

  CREDIT_SCORE_SERVICE_URL: http://credit-score-service

  DOCUMENT_SERVICE_URL: http://document-service

  LOG_LEVEL: INFO

  MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE: "*"

  MANAGEMENT_ENDPOINT_PROMETHEUS_ENABLED: "true"
  