apiVersion: v1
kind: ConfigMap

metadata:
  name: payment-service-config
  namespace: banking

data:

  SPRING_APPLICATION_NAME: payment-service

  SERVER_PORT: "8080"

  DB_HOST: postgres-payment

  DB_PORT: "5432"

  DB_NAME: paymentdb

  KAFKA_BOOTSTRAP_SERVERS: kafka:9092

  REDIS_HOST: redis

  REDIS_PORT: "6379"

  PAYMENT_GATEWAY_URL: https://sandbox.payment-gateway.com

  LOG_LEVEL: INFO

  MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE: "*"

  MANAGEMENT_ENDPOINT_PROMETHEUS_ENABLED: "true"