apiVersion: v1
kind: ConfigMap

metadata:
  name: fraud-service-config
  namespace: banking

data:

  SPRING_APPLICATION_NAME: fraud-service

  SERVER_PORT: "8080"

  DB_HOST: postgres-fraud

  DB_PORT: "5432"

  DB_NAME: frauddb

  REDIS_HOST: redis

  REDIS_PORT: "6379"

  KAFKA_BOOTSTRAP_SERVERS: kafka:9092

  PAYMENT_SERVICE_URL: http://payment-service

  CUSTOMER_SERVICE_URL: http://customer-service

  RISK_ENGINE_URL: http://risk-engine-service

  ML_MODEL_ENDPOINT: http://ml-model-service:8501/v1/models/fraud:predict

  MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE: "*"

  MANAGEMENT_ENDPOINT_PROMETHEUS_ENABLED: "true"

  LOG_LEVEL: INFO