apiVersion: v1
kind: Secret
metadata:
  name: kafka-kraft-config
  namespace: banking
type: Opaque
stringData:
  # This ID must remain unchanged after any Kafka volume has been formatted.
  KAFKA_CLUSTER_ID: "vuDPlGdHUs-Or165BmD6RA"
