apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - rbac.yaml
  - prometheus-config.yaml
  - prometheus-rules.yaml
  - services.yaml
  - statefulset.yaml
