apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - kraft-secret.yaml
  - kafka-configmap.yaml
  - services.yaml
  - statefulsets.yaml
  - pdb.yaml
  - networkpolicy.yaml
  - topics-job.yaml
