apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: kafka-controller-pdb
  namespace: banking
spec:
  minAvailable: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: kafka
      app.kubernetes.io/component: controller
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: kafka-broker-pdb
  namespace: banking
spec:
  minAvailable: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: kafka
      app.kubernetes.io/component: broker
