apiVersion: v1
kind: ResourceQuota

metadata:
  name: banking-resource-quota
  namespace: enterprise-banking

spec:
  hard:

    requests.cpu: "8"

    requests.memory: 16Gi

    limits.cpu: "16"

    limits.memory: 32Gi

    pods: "100"

    services: "30"

    persistentvolumeclaims: "20"

    configmaps: "30"

    secrets: "30"
    