apiVersion: v1
kind: Secret

metadata:
  name: fraud-service-secret
  namespace: banking

type: Opaque

stringData:

  DB_USERNAME: fraud_user

  DB_PASSWORD: fraud_password

  JWT_SECRET: replace-with-production-secret

  MODEL_API_TOKEN: replace-with-model-api-token

  AES_ENCRYPTION_KEY: replace-with-256-bit-key
  