apiVersion: v1
kind: Secret

metadata:
  name: loan-service-secret
  namespace: banking

type: Opaque

stringData:

  DB_USERNAME: loan_user

  DB_PASSWORD: loan_password

  JWT_SECRET: replace-with-production-secret

  ENCRYPTION_KEY: replace-with-256-bit-key
  