apiVersion: v1
kind: Secret

metadata:
  name: audit-service-secret
  namespace: banking

type: Opaque

stringData:

  DB_USERNAME: audit_user

  DB_PASSWORD: audit_password

  JWT_SECRET: replace-with-production-secret

  ELASTIC_USERNAME: elastic

  ELASTIC_PASSWORD: replace-me

  OPENSEARCH_PASSWORD: replace-me