apiVersion: v1
kind: Service

metadata:
  name: audit-service
  namespace: banking

  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/path: "/actuator/prometheus"

  labels:
    app: audit-service

spec:
  selector:
    app: audit-service

  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8080

  type: ClusterIP
