terminationMessagePath: /dev/termination-log

terminationMessagePolicy: File

securityContext:

  allowPrivilegeEscalation: false

  readOnlyRootFilesystem: false

  runAsNonRoot: true

  runAsUser: 1000

  capabilities:

    drop:

      - ALL
